import React, { useEffect, useState } from 'react';
import { useSelector } from 'react-redux';
import { Tabs, Button, Card, Tag, Table, Modal, Form, Input, Select, Switch, message, Spin } from 'antd';
import { 
  BarChart3, 
  TrendingUp, 
  DollarSign, 
  ShoppingBag, 
  Users, 
  Package, 
  FileText, 
  Download, 
  Plus, 
  Sparkles,
  Flame,
  Clock,
  ShieldCheck
} from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip as RechartsTooltip, BarChart, Bar, CartesianGrid } from 'recharts';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';

export const AdminDashboard = () => {
  const { token, user } = useSelector((state) => state.auth);

  const [metrics, setMetrics] = useState(null);
  const [menuItems, setMenuItems] = useState([]);
  const [inventoryValuation, setInventoryValuation] = useState(null);
  const [auditLogs, setAuditLogs] = useState([]);
  const [loading, setLoading] = useState(true);

  const [createMenuModalOpen, setCreateMenuModalOpen] = useState(false);
  const [form] = Form.useForm();

  const loadData = async () => {
    setLoading(true);
    try {
      const [resDash, resMenu, resVal, resAudit] = await Promise.all([
        fetch('/api/analytics/dashboard', { headers: { Authorization: `Bearer ${token}` } }),
        fetch('/api/menu'),
        fetch('/api/inventory/valuation', { headers: { Authorization: `Bearer ${token}` } }),
        fetch('/api/analytics/audit-logs', { headers: { Authorization: `Bearer ${token}` } })
      ]);

      const dataDash = await resDash.json();
      const dataMenu = await resMenu.json();
      const dataVal = await resVal.json();
      const dataAudit = await resAudit.json();

      if (dataDash.success) setMetrics(dataDash.data);
      if (dataMenu.success) setMenuItems(dataMenu.data);
      if (dataVal.success) setInventoryValuation(dataVal.data);
      if (dataAudit.success) setAuditLogs(dataAudit.data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [token]);

  // Export Sales Report to PDF
  const exportPDF = () => {
    const doc = new jsPDF();
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('ORBIT CANTEEN - SALES & ANALYTICS REPORT', 14, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated Date: ${new Date().toLocaleString()}`, 14, 30);
    doc.text(`Generated By: ${user?.name} (Admin)`, 14, 36);

    doc.line(14, 42, 196, 42);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('1. Executive Financial Summary', 14, 52);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Revenue: $${metrics?.totalRevenue || '0.00'}`, 14, 60);
    doc.text(`Total Orders Fulfilled: ${metrics?.totalOrdersCount || '0'}`, 14, 66);
    doc.text(`Average Order Value (AOV): $${metrics?.averageOrderValue || '0.00'}`, 14, 72);
    doc.text(`FIFO Total Inventory Valuation: $${inventoryValuation?.fifoTotalValuation || '0.00'}`, 14, 78);

    doc.save(`OrbitCanteen_Report_${Date.now()}.pdf`);
    message.success('PDF Report downloaded!');
  };

  // Export Sales & Inventory to Excel (.xlsx)
  const exportExcel = () => {
    const salesData = metrics?.salesTrends || [];
    const menuData = menuItems.map(m => ({
      ID: m.id,
      Name: m.name,
      Category: m.category,
      Price: m.price,
      Rating: m.rating,
      Available: m.isAvailable ? 'Yes' : 'No'
    }));

    const wb = XLSX.utils.book_new();
    const wsSales = XLSX.utils.json_to_sheet(salesData);
    const wsMenu = XLSX.utils.json_to_sheet(menuData);

    XLSX.utils.book_append_sheet(wb, wsSales, 'Sales Trends');
    XLSX.utils.book_append_sheet(wb, wsMenu, 'Menu Inventory');

    XLSX.writeFile(wb, `OrbitCanteen_Data_${Date.now()}.xlsx`);
    message.success('Excel Report exported!');
  };

  // Generate PO
  const handleGeneratePO = async () => {
    try {
      const res = await fetch('/api/inventory/generate-po', {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (data.success) {
        message.success(`Generated ${data.count} Purchase Orders for suppliers!`);
        loadData();
      }
    } catch (e) {
      message.error('Failed to generate PO');
    }
  };

  // Toggle Happy Hour
  const handleToggleHappyHour = async (itemId, currentVal) => {
    try {
      const res = await fetch(`/api/menu/${itemId}/happy-hour`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({ isHappyHourDiscount: !currentVal, discountPercent: 15 })
      });
      const data = await res.json();
      if (data.success) {
        message.success(`Toggled Happy Hour for item.`);
        loadData();
      }
    } catch (e) {
      message.error('Failed to toggle happy hour.');
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-4 space-y-6">
      
      {/* Real-time Rolling Sales Ticker Header */}
      <div className="glass-panel-glow p-6 rounded-3xl space-y-4">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl flex items-center justify-center" style={{ background: 'var(--blue)', borderRadius: 'var(--r-md)' }}>
              <BarChart3 className="w-6 h-6 text-white" style={{ color: '#fff' }} />
            </div>
            <div>
              <h2 className="text-2xl font-bold font-display">
                Analytics
              </h2>
              <p className="text-xs text-slate-400">
                Sales overview, menu management, and inventory · {user?.name}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button
              icon={<FileText className="w-4 h-4 text-cyan-400" />}
              onClick={exportPDF}
              className="spring-button text-xs font-semibold"
            >
              Export PDF
            </Button>
            <Button
              type="primary"
              icon={<Download className="w-4 h-4" />}
              onClick={exportExcel}
              className="spring-button text-xs font-bold bg-gradient-to-r from-cyan-500 to-purple-600 border-0"
            >
              Export Excel (.xlsx)
            </Button>
          </div>
        </div>

        {/* Sales Ticker Cards */}
        {metrics && (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 pt-2">
            <div className="p-4 glass-panel rounded-2xl border-cyan-500/30">
              <span className="text-[11px] text-slate-400 block uppercase font-mono">Total Revenue</span>
              <h3 className="text-2xl font-bold font-mono text-cyan-300 mt-1">${metrics.totalRevenue}</h3>
            </div>
            <div className="p-4 glass-panel rounded-2xl border-purple-500/30">
              <span className="text-[11px] text-slate-400 block uppercase font-mono">Total Orders</span>
              <h3 className="text-2xl font-bold font-mono text-purple-300 mt-1">{metrics.totalOrdersCount}</h3>
            </div>
            <div className="p-4 glass-panel rounded-2xl border-emerald-500/30">
              <span className="text-[11px] text-slate-400 block uppercase font-mono">Average Order Value</span>
              <h3 className="text-2xl font-bold font-mono text-emerald-300 mt-1">${metrics.averageOrderValue}</h3>
            </div>
            <div className="p-4 glass-panel rounded-2xl border-amber-500/30">
              <span className="text-[11px] text-slate-400 block uppercase font-mono">FIFO Valuation</span>
              <h3 className="text-2xl font-bold font-mono text-amber-300 mt-1">
                ${inventoryValuation?.fifoTotalValuation || '0.00'}
              </h3>
            </div>
          </div>
        )}
      </div>

      <Tabs
        defaultActiveKey="charts"
        items={[
          {
            key: 'charts',
            label: (
              <span className="flex items-center gap-2 font-bold text-sm">
                <TrendingUp className="w-4 h-4 text-cyan-400" /> Revenue & Demand Charts
              </span>
            ),
            children: metrics && (
              <div className="space-y-6 pt-2">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                  
                  {/* Revenue Trends Line Chart */}
                  <div className="glass-panel p-5 rounded-2xl space-y-3">
                    <h4 className="text-sm font-bold text-slate-200 flex items-center gap-2">
                      <TrendingUp className="w-4 h-4 text-cyan-400" /> Weekly Revenue Stream ($)
                    </h4>
                    <div className="h-64 w-full">
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={metrics.salesTrends}>
                          <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                          <XAxis dataKey="day" stroke="#64748B" />
                          <YAxis stroke="#64748B" />
                          <RechartsTooltip contentStyle={{ backgroundColor: '#0E131F', borderColor: '#00F2FE' }} />
                          <Line type="monotone" dataKey="revenue" stroke="#00F2FE" strokeWidth={3} dot={{ r: 5 }} />
                        </LineChart>
                      </ResponsiveContainer>
                    </div>
                  </div>

                  {/* Top Selling Items Bar Chart */}
                  <div className="glass-panel p-5 rounded-2xl space-y-3">
                    <h4 className="text-sm font-bold text-slate-200 flex items-center gap-2">
                      <ShoppingBag className="w-4 h-4 text-purple-400" /> Top 5 Best-Selling Items
                    </h4>
                    <div className="h-64 w-full">
                      <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={metrics.topSellingItems}>
                          <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                          <XAxis dataKey="name" stroke="#64748B" />
                          <YAxis stroke="#64748B" />
                          <RechartsTooltip contentStyle={{ backgroundColor: '#0E131F', borderColor: '#9B51E0' }} />
                          <Bar dataKey="count" fill="#9B51E0" radius={[8, 8, 0, 0]} />
                        </BarChart>
                      </ResponsiveContainer>
                    </div>
                  </div>

                </div>
              </div>
            )
          },
          {
            key: 'menu_mgmt',
            label: (
              <span className="flex items-center gap-2 font-bold text-sm">
                <Sparkles className="w-4 h-4 text-amber-400" /> Menu Catalog & Happy Hour
              </span>
            ),
            children: (
              <div className="space-y-4 pt-2">
                <div className="flex justify-between items-center">
                  <h4 className="text-sm font-bold text-slate-200">Active Menu Catalog</h4>
                  <Button
                    type="primary"
                    icon={<Plus className="w-4 h-4" />}
                    onClick={() => setCreateMenuModalOpen(true)}
                    className="spring-button text-xs font-bold bg-cyan-500 border-0"
                  >
                    Add Menu Item
                  </Button>
                </div>

                <div className="glass-panel p-4 rounded-2xl overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead>
                      <tr className="text-slate-400 border-b border-slate-800 pb-2">
                        <th className="p-2">Name</th>
                        <th className="p-2">Category</th>
                        <th className="p-2">Base Price</th>
                        <th className="p-2">Dietary Tags</th>
                        <th className="p-2">Happy Hour</th>
                        <th className="p-2">Availability</th>
                      </tr>
                    </thead>
                    <tbody>
                      {menuItems.map((item) => (
                        <tr key={item.id} className="border-b border-slate-800/60 hover:bg-slate-900/40">
                          <td className="p-2 font-bold text-slate-200">{item.name}</td>
                          <td className="p-2 text-slate-400">{item.category}</td>
                          <td className="p-2 font-mono text-cyan-400">${item.price.toFixed(2)}</td>
                          <td className="p-2">
                            {item.dietaryTags?.map(t => <Tag key={t} color="cyan">{t}</Tag>)}
                          </td>
                          <td className="p-2">
                            <Switch
                              checked={item.isHappyHourDiscount}
                              onChange={() => handleToggleHappyHour(item.id, item.isHappyHourDiscount)}
                            />
                            {item.isHappyHourDiscount && <span className="ml-2 text-amber-400 font-bold">15% OFF</span>}
                          </td>
                          <td className="p-2">
                            <Tag color={item.isAvailable ? 'green' : 'error'}>
                              {item.isAvailable ? 'Available' : 'Out of Stock'}
                            </Tag>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )
          },
          {
            key: 'valuation_po',
            label: (
              <span className="flex items-center gap-2 font-bold text-sm">
                <Package className="w-4 h-4 text-emerald-400" /> FIFO Valuation & PO Generator
              </span>
            ),
            children: (
              <div className="space-y-4 pt-2">
                <div className="glass-panel p-5 rounded-2xl flex justify-between items-center flex-wrap gap-4">
                  <div>
                    <h4 className="text-sm font-bold text-slate-200">FIFO Stock Valuation</h4>
                    <p className="text-xs text-slate-400 mt-0.5">Calculated using First-In, First-Out unit cost modeling.</p>
                  </div>
                  <Button
                    type="primary"
                    onClick={handleGeneratePO}
                    className="spring-button text-xs font-bold bg-emerald-500 border-0"
                  >
                    Generate Purchase Orders for Suppliers →
                  </Button>
                </div>
              </div>
            )
          },
          {
            key: 'audit_logs',
            label: (
              <span className="flex items-center gap-2 font-bold text-sm">
                <ShieldCheck className="w-4 h-4 text-rose-400" /> Audit Logs
              </span>
            ),
            children: (
              <div className="glass-panel p-4 rounded-2xl space-y-3 pt-2">
                <h4 className="text-xs font-bold text-slate-300 uppercase">System Security & Audit Activity</h4>
                <div className="space-y-2">
                  {auditLogs.map((log) => (
                    <div key={log.id} className="p-3 bg-slate-900/60 rounded-xl text-xs flex justify-between border border-slate-800">
                      <div>
                        <span className="font-mono font-bold text-cyan-400 mr-2">[{log.action}]</span>
                        <span className="text-slate-200">{log.details}</span>
                      </div>
                      <div className="text-right">
                        <span className="text-slate-400 block">{log.performedBy}</span>
                        <span className="text-[10px] text-slate-500 font-mono">{new Date(log.timestamp).toLocaleString()}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )
          }
        ]}
      />

    </div>
  );
};

export default AdminDashboard;
